trigger:
  branches:
    include:
      - new-main
 
pr: none
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  imageName: 'teams-project-management'
 
steps:
# Checkout code from GitHub
- checkout: self

# Build and push Docker image to ACR
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: 'ecoverde-svc'   # <-- your ACR service connection
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
 
# Deploy to Azure Web App for Containers
- task: AzureWebAppContainer@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: 'ecoverde-prod-svc'          # <-- same as your other project
    appName: 'app-ecoverde-prod'           # <-- your app service name
    containers: 'acrecoverdeprodd.azurecr.io/$(imageName):latest'